apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xegxqts3g-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xegxqts3g-dotnet-basic